language: node_js
node_js:
  - "node"
script:
  - npm t
  - npm run coveralls
  - npm run eslint
  - webpack
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: docs
  on:
    branch: master
